In [1]:
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7],[3,6,9,6]])
y = np.array([1,2,2])
y_pre = np.array([1,3,2])

In [2]:
"Standardize the dataset"
def standardize(X):
    mean = np.mean(X, axis = 0)
    std = np.std(X, axis = 0)
    res = X
    for col in range(X.shape[1]):
        if std[col]:
            res[:,col] = (X[:, col]-mean[col])/std[col]
    return res

print(standardize(arr))

[[-1 -1 -1 -1]
 [ 1  0  0  1]
 [ 0  0  1  0]]


In [3]:
"Normalize the dataset"
def normalize(X):
    res = X
    a = np.min(X, axis = 0)
    b = np.max(X, axis = 0)
    for row in range(X.shape[0]):
        if b[row]>a[row]:
            res[row, :] = (X[row, :]-a[row])/(b[row]-a[row])
    return res

print(normalize(arr))

[[0 0 0 0]
 [2 1 1 2]
 [0 0 1 0]]


In [4]:
import math
import collections
"Calculate the entropy of label array y"
def entropy(y):
    entropy = 0
    values = collections.Counter(y).values()
    for v in values:
        p = v/sum(values)
        entropy += -p*math.log2(p)
    return entropy

print(entropy(y)) 

0.9182958340544896


In [5]:
"Calculate the MSE between the actual value and the prediction"
def mean_squared_error(y, y_pre):
    return sum((y-y_pre)**2)/len(y)

mean_squared_error(y,y_pre)

0.3333333333333333

In [6]:
"Calculate the variance based on features of a dataset X"
def variance(X):
    mean = np.ones(np.shape(arr))*np.mean(arr,axis=0)
    n = X.shape[0]
    variance = (1/n)*np.diag((X-mean).T.dot(X-mean))
    return variance

variance(arr)

array([0.88888889, 0.22222222, 0.22222222, 0.88888889])

In [7]:
"Calculate the standard deviation based on features of a dataset X"
def std_dev(X):
    return np.sqrt(variance(X))

std_dev(arr)

array([0.94280904, 0.47140452, 0.47140452, 0.94280904])

In [8]:
"Calculate the euclidean distance between two vectors"
def euclidean_distance(x1, x2):
    d = 0
    for i in range(len(x1)):
        d += (x1[i] - x2[i])**2
    return np.sqrt(d)

euclidean_distance(y,y_pre) 

1.0

In [9]:
"Compare the prediction with actual value and return the accuracy in classification problems"
def accuracy(y, y_pre):
    return sum(y==y_pre)/len(y)

accuracy(y,y_pre)

0.6666666666666666